on:
  push:
    branches-ignore:
      - "**"
    paths:
      - "images/airflow/**"

name: Trigger AWS CodeBuild to deploy Aiflow Fargate services

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <AWS_REGION>

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        with:
          project-name: <CODEBUILD_PROJECT_NAME>
          buildspec-override: images/airflow_buildspec.yml
          env-vars-for-codebuild: |
            IMAGE_TAG,
            REPOSITORY_URI,
        env:
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY_URI: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com
